export 'people_provider.dart' show peopleProvider;
export 'location_providers.dart' show locationsProvider;
export '../models/relationship_provider.dart' show relationshipsProvider;
export 'government_extension2.dart' show governmentTypeProvider,positionsProvider,roleBySizeProvider;
export 'location_role_provider.dart' show locationRolesProvider;
export 'pending_roles_provider.dart' show pendingRolesProvider;
export 'role_meta_provider.dart' show roleMetaProvider;
export 'shop_data_providers.dart' show shopNamesProvider,shopQualitiesProvider, genericServicesProvider,specialtyServicesProvider;
export 'anecestries_provider.dart' show ancestriesProvider;
export 'resonant_argument_provider.dart' show resonantArgumentsProvider;
export 'quirk_provider.dart' show quirksProvider;
export "given_names_provider.dart" show givenNamesProvider;
export "surname_provider.dart" show surnamesProvider;
export "town_provider.dart" show townsProvider;
export "random_encounters_provider.dart" show randomEncountersProvider;
export "physical_template_provider.dart" show physicalTemplatesProvider;
export "clothing_template_provider.dart" show clothingTemplatesProvider;
export "shop_template_provider.dart" show shopTemplateProvider;
export "location_template_provider.dart" show locationTemplatesProvider;
export "../search_models_providers_listeners/search_memory.dart" show peopleSearchProvider,locationsSearchProvider;
export 'firestore_service_provider.dart';
export 'shop_filter_provider.dart';
export 'todo_provider.dart' show authServiceProvider;