// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmfJHeLAvmdhOZxEA_c7pbQKv3S8zb4jg',
    appId: '1:981250106850:web:afa9d9bcc193bc470c85bb',
    messagingSenderId: '981250106850',
    projectId: 'flutter-todo-app-68411',
    authDomain: 'flutter-todo-app-68411.firebaseapp.com',
    storageBucket: 'flutter-todo-app-68411.firebasestorage.app',
    measurementId: 'G-5GRK87BK0B',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZgSoQQrCFL_G0K-aFkQiOUH91W-jHBsc',
    appId: '1:981250106850:ios:b6377d4f69d770a40c85bb',
    messagingSenderId: '981250106850',
    projectId: 'flutter-todo-app-68411',
    storageBucket: 'flutter-todo-app-68411.firebasestorage.app',
    iosClientId: '981250106850-71l0ohp2cr4lps8kgvmgkejnjvmldac7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firetown',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZgSoQQrCFL_G0K-aFkQiOUH91W-jHBsc',
    appId: '1:981250106850:ios:81236c27231623510c85bb',
    messagingSenderId: '981250106850',
    projectId: 'flutter-todo-app-68411',
    storageBucket: 'flutter-todo-app-68411.firebasestorage.app',
    iosClientId: '981250106850-29d661nmac628ridmqajcr6ltdqcoh20.apps.googleusercontent.com',
    iosBundleId: 'com.example.hivetown',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpt7XBqlsLnfKtgxeL3VGcWrQvmiZuVgI',
    appId: '1:981250106850:android:49cf1dcf5dcae51c0c85bb',
    messagingSenderId: '981250106850',
    projectId: 'flutter-todo-app-68411',
    storageBucket: 'flutter-todo-app-68411.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmfJHeLAvmdhOZxEA_c7pbQKv3S8zb4jg',
    appId: '1:981250106850:web:59c30da6645845be0c85bb',
    messagingSenderId: '981250106850',
    projectId: 'flutter-todo-app-68411',
    authDomain: 'flutter-todo-app-68411.firebaseapp.com',
    storageBucket: 'flutter-todo-app-68411.firebasestorage.app',
    measurementId: 'G-7MHK68T2QZ',
  );

}